# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "muuuuuuushroom"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# project page: https://muuuuuuushroom.github.io/cv-arxiv-daily/
# keywords to search
keywords:
  "Multimodal":
      filters: ["Multimodal", "Vision and Language", "Vision-Language", "Grounding", "Query-based"]
  "Counting":
      filters: ["Counting", "Crowd Counting", "class-agnostic counting", "referring expression counting", "multimodal counting"]
  "Dense Prediction": 
      filters: ["Dense Prediction", "Semantic Segmentation", "Depth Estimation", "Image Matting", "Object Detection", "Instance Segmentation", "Pose Estimation", "Image Denoising"]
  "Model Components": 
      filters: ["Upsampling", "Downsampling", "Encoder-Decoder", "Feature Sampling", "Dynamic Upsampling", "Task-agnostic Upsampling", "Query Group"]
  "Unified Architectures":
      filters: ["Unified Perceptual Parsing", "Generalist Vision Model", "One Model for All Tasks", "Universal Image Segmentation", "Multi-task Dense Prediction"]
  "Mechanism Specific":
      filters: ["Query-based Learning", "Task Prompts", "Mask Classification", "Transformer Decoder", "Unified Output Space"]
  "Foundation Models":
      filters: ["Vision Foundation Models", "Large Vision Models", "Vision Model Scaling", "Scaling Vision Models", "Scaling Laws for Vision Models", "Scaling Vision Transformers", "Scaling Laws for Vision Transformers", "LVM"]
  "VTON":
      filters: ["Virtual Try-On", "VTON", "Clothing Try-On", "3D Virtual Try-On", "Multi-view Virtual Try-On", "Try-On Synthesis"]
    # "SLAM": 
    #     filters: ["SLAM", "Visual Odometry"]
    # "SFM":
    #     filters: ["SFM", "Structure from Motion"]
    # "Visual Localization":
    #     filters: ["Visual Localization","Camera Localization",
    #               "Camera Re-localisation","Loop Closure Detection",
    #               "visual place recognition","image retrieval"]
    # "Keypoint Detection":
    #     filters: ["Keypoint Detection", "Feature Descriptor"]
    # "Image Matching":
    #     filters: ["Image Matching", "Keypoint Matching", 
    #               "Line Segment Detection", "Local Feature Matching"]
    # "NeRF":
    #     filters: ["NeRF"]
